# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-TwoStage
version:      0.01_01
version_from: lib/Template/Plugin/TwoStage.pm
installdirs:  site
requires:
    Class::Data::Inheritable:      0
    Cwd:                           0
    Digest::SHA1:                  0
    File::Path:                    0
    File::Spec:                    0
    Template:                      0
    Test::More:                    0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
