--- #YAML:1.0
name:               Template-Plugin-TwoStage
version:            0.03
abstract:           two stage processing of template blocks with first stage caching
author:
    - Alexander Kühne <alexk@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Data::Inheritable:  0
    constant:             0
    Cwd:                  0
    Digest::SHA1:         0
    File::Path:           0
    File::Spec:           0
    Template:             0
    Test::More:           0
    URI::Escape:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
