---
abstract: 'two stage processing of template blocks with first stage caching'
author:
  - 'Alexander Kühne <alexk@cpan.org>'
build_requires:
  Template::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101831, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-TwoStage
requires:
  Class::Data::Inheritable: 0
  Cwd: 0
  Digest::SHA1: 0
  Encode: 0
  File::Path: 0
  File::Spec: 0
  Template: 2.01
  Template::Exception: 0
  Template::Parser: 0
  Template::Plugin: 0
  Template::Provider: 0
  URI::Escape: 0
  constant: 0
  perl: 5.006
version: 0.05
